esphome: 
    name: baros-slave
    on_boot:
      - priority: -100.0
        then:
          - binary_sensor.template.publish:
              id: clean_system_slave
              state: false
          - binary_sensor.template.publish:
              id: pi_started_slave
              state: false
          - delay: 3s
          - light.turn_on: led_rgb2

esp32:
  # board: esp32dev
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

logger:
  logs:
    interval: NONE
    binary_sensor: NONE

globals:
  - id: liquid1_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid2_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid3_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid4_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid5_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid6_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid7_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid8_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid1_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid2_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid3_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid4_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid5_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid6_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid7_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid_time_threshold
    type: unsigned long
    initial_value: '1000'  # 默认1秒阈值，可调整

wifi:  
  networks:
    - ssid: "Latent Spice"
      password: "bqsj123456"
    - ssid: "bqsj-nono"
      password: "Qzpm!234.."
  fast_connect: true
  power_save_mode: none

ota: 
  - platform: esphome
web_server: 
  port: 80

uart:
  - id: uart_com
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    
  - id: uart_pi
    tx_pin: 20
    rx_pin: 19
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "0xAA"
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);
            if (direction == UARTDirection::UART_DIRECTION_RX) {
              if(bytes[0] == 0x0f && bytes[7] == 0xAA) {
                uint8_t module = bytes[2];
                uint16_t data1 = bytes[3] << 8 | bytes[4];
                uint16_t data2 = bytes[5] << 8 | bytes[6];
                if(module == 0 && data1 == 1 && data2 == 1) {
                  id(clean_system_slave).publish_state(true);
                }
                if (module == 0xFF) {
                  id(pi_started_slave).publish_state(true);
                } 
              }
            }

packet_transport:
  platform: uart
  uart_id: uart_com
  binary_sensors:
    - tank1_slave
    - tank2_slave
    - tank3_slave
    - tank4_slave
    - tank5_slave
    - tank6_slave
    - tank7_slave
    - tank8_slave
    - liquid1_slave
    - liquid2_slave
    - liquid3_slave
    - liquid4_slave
    - liquid5_slave
    - liquid6_slave
    - liquid7_slave
    - liquid8_slave
    - clean_system_slave
    - pi_started_slave
light:
  - platform: esp32_rmt_led_strip
    id: led_rgb2
    name: "RMT RGB2"
    chipset: WS2812
    rgb_order: GRB
    pin: 5 #板子好的时候
    # pin: 8
    num_leds: 300
    on_turn_on:
      - light.turn_on:
          id: led_rgb2
          red: 0.598
          green: 0.688
          blue: 1.0
          brightness: 1.0

binary_sensor:
  - platform: packet_transport
    name: Wifi Status
    provider: baros
    remote_id: wifi_status_main
    internal: false
    id: wifi_status


  - platform: packet_transport
    name: Server Status
    provider: baros
    remote_id: server_status_main
    internal: false
    id: server_status

  - platform: template
    name: PI Started
    id: pi_started_slave
    on_press:
      - then:
          - script.execute:
              id: send_to_pi
              module: 0xFF
              data1: 0
              data2: 0

  - platform: packet_transport
    name: Recipe Pouring
    provider: baros
    remote_id: pouring1
    internal: false
    on_press:
      - script.execute:
          id: send_to_pi
          module: 0 
          data1: 2
          data2: 1
    on_release:
      - script.execute:
          id: send_to_pi
          module: 0
          data1: 2
          data2: 0
  - platform: template
    name: Clean System
    id: clean_system_slave
    

  - platform: gpio
    pin: 
      number: 42
      inverted: true
    name: Tank5
    id: tank5_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 5
            data2: !lambda "return x;"
    
  - platform: gpio
    pin: 
      number: 41
      inverted: true
    name: Tank6
    id: tank6_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 6
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 40
      inverted: true
    name: Tank7
    id: tank7_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 7
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 39
      inverted: true
    name: Tank8
    id: tank8_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 8
            data2: !lambda "return x;"
    
  - platform: gpio
    pin: 
      number: 38
      inverted: true
    name: Tank4
    id: tank4_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 4
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 37
      inverted: true
    name: Tank3
    id: tank3_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 3
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 36
      inverted: true
    name: Tank2
    id: tank2_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 2
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 35
      inverted: true
    name: Tank1
    id: tank1_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 1
            data2: !lambda "return x;"

  - platform: gpio
    pin:
      number: 11
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid1
    id: liquid1_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid1_last_time) = now;
            ESP_LOGI("liquid1", "Liquid1 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid1 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid1 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid2
    id: liquid2_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid2_last_time) = now;
            ESP_LOGI("liquid2", "Liquid2 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid2 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid2 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        output: false
        open_drain: false
        pullup: false
        pulldown: true
      inverted: true
    name: Liquid3
    id: liquid3_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid3_last_time) = now;
            ESP_LOGI("liquid3", "Liquid3 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid3 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid3 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid4
    id: liquid4_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid4_last_time) = now;
            ESP_LOGI("liquid4", "Liquid4 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid4 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid4 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 48
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid5
    id: liquid5_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid5_last_time) = now;
            ESP_LOGI("liquid5", "Liquid5 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid5 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid5 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 47
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid6
    id: liquid6_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid6_last_time) = now;
            ESP_LOGI("liquid6", "Liquid6 开启，记录时间: %lu ms", now);
    on_release:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid6_last_time) = now;
  - platform: gpio
    pin:
      number: 21
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid7
    id: liquid7_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid7_last_time) = now;
            ESP_LOGI("liquid7", "Liquid7 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid7 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid7 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 10
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid8
    id: liquid8_slave
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            
            // 检查所有液位传感器到Liquid8的时间间隔
            for (int i = 1; i <= 7; i++) {
              unsigned long last_time = 0;
              unsigned long interval = 0;
              const char* sensor_name = "";
              
              switch(i) {
                case 1:
                  last_time = id(liquid1_last_time);
                  sensor_name = "液位1";
                  break;
                case 2:
                  last_time = id(liquid2_last_time);
                  sensor_name = "液位2";
                  break;
                case 3:
                  last_time = id(liquid3_last_time);
                  sensor_name = "液位3";
                  break;
                case 4:
                  last_time = id(liquid4_last_time);
                  sensor_name = "液位4";
                  break;
                case 5:
                  last_time = id(liquid5_last_time);
                  sensor_name = "液位5";
                  break;
                case 6:
                  last_time = id(liquid6_last_time);
                  sensor_name = "液位6";
                  break;
                case 7:
                  last_time = id(liquid7_last_time);
                  sensor_name = "液位7";
                  break;
              }
              
              if (last_time > 0) {
                interval = now - last_time;
                ESP_LOGI("interval", "液位8开启 - 距离%s上次开启间隔: %lu ms (阈值: %lu ms)", sensor_name, interval, id(liquid_time_threshold));
                
                // 存储间隔到对应的全局变量
                switch(i) {
                  case 1: id(liquid1_8_interval) = interval; break;
                  case 2: id(liquid2_8_interval) = interval; break;
                  case 3: id(liquid3_8_interval) = interval; break;
                  case 4: id(liquid4_8_interval) = interval; break;
                  case 5: id(liquid5_8_interval) = interval; break;
                  case 6: id(liquid6_8_interval) = interval; break;
                  case 7: id(liquid7_8_interval) = interval; break;
                }
                
                // 检查是否在阈值范围内
                if (interval <= id(liquid_time_threshold)) {
                  ESP_LOGI("interval", "液位8-%s时间间隔在阈值内，正常", sensor_name);
                } else {
                  ESP_LOGW("interval", "液位8-%s时间间隔超出阈值，可能异常", sensor_name);
                }
              } else {
                ESP_LOGI("interval", "液位8开启 - %s尚未检测到", sensor_name);
              }
            }
            
            id(liquid8_last_time) = now;
    on_release:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid8_last_time) = now;

script:
  - id: send_to_pi
    mode: queued
    parameters:
      module: uint8_t
      data1: uint16_t
      data2: uint16_t
    then:
      - delay: 100ms
      - lambda: |-
          uint8_t frame[8] = {
            0x0f, 0x00, 
            module,
            (uint8_t)((data1 >> 8) & 0xff),
            (uint8_t)(data1 & 0xff),
            (uint8_t)((data2 >> 8) & 0xff),
            (uint8_t)(data2 & 0xff),
            0xAA
          };
          id(uart_pi).write_array(frame, 8);


  - id: update_connection_status
    mode: single
    then:
      - script.execute:
          id: send_to_pi
          module: 0x00
          data1: 0x3
          data2: !lambda "return id(wifi_status).state;"
      - script.execute:
          id: send_to_pi
          module: 0x00
          data1: 0x04
          data2: !lambda "return id(server_status).state;"

  - id: update_all_tank_status
    mode: single
    then:
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 1
          data2: !lambda "return id(tank1_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 2
          data2: !lambda "return id(tank2_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 3
          data2: !lambda "return id(tank3_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 4
          data2: !lambda "return id(tank4_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 5
          data2: !lambda "return id(tank5_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 6
          data2: !lambda "return id(tank6_slave).state;"
      - script.execute:
          id: send_to_pi
          module: 1
          data1: 7
          data2: !lambda "return id(tank7_slave).state;"

button:
  - platform: template
    name: Test UART
    on_press:
      then:
        - logger.log: "Test UART"
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 3
            data2: 0

  - platform: template
    name: Test MP4
    on_press: 
      then:
        - script.execute:
            id: send_to_pi
            module: 0 
            data1: 2
            data2: 1
        - delay: 5s
        - script.execute:
            id: send_to_pi
            module: 0
            data1: 2
            data2: 0

interval:
  - interval: 30s
    then:
      - script.execute: update_all_tank_status
    
  - interval: 10s
    then:
      - binary_sensor.template.publish:
          id: wifi_status
          state: 'false'
      - binary_sensor.template.publish:
          id: server_status
          state: 'false'
      - delay: 2s
      - script.execute: update_connection_status